version: '2'
services:
    vmweb-cassandra:
        container_name: vmweb-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/vmweb/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    vmweb-cassandra-node:
        image: cassandra:3.9
        links:
            - vmweb-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    vmweb-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: vmweb-cassandra-migration
        links:
            - vmweb-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
